87 possibility to add more copy of the same card
Tarjetakuna/Tarjetakuna pull request #100
Opened 2023-05-17 21:18 UTC by Bjolidon

You can now add more copy of the same card in your collection through the single card fragment. You may have to use deleteDatabase from LocalDatabaseProvider once to make it work as I modified DBMagicCard

2023-05-17 23:05 UTC, Cocograal requested changes

2023-05-17 23:05 UTC, Cocograal commented on app/src/main/java/com/github/sdp/tarjetakuna/database/UserRTDB.kt
> +                if (currentValue != null) {
What is the point of doing this? either way you set the value to 0?

2023-05-18 13:17 UTC, Cocograal submitted a review, later dismissed
Thanks for the changes

2023-05-18 15:16 UTC, KelvinKappeler requested changes
I don't have much to say. Congratulations on your work, well done! However, please correct the tests in order to be able to merge in the main without problems (and to check the total coverage).

In addition, it does not seem to me that you have tested the new MagicCard with the quantity added

2023-05-18 15:16 UTC, KelvinKappeler commented on app/src/main/res/layout/cards_recycler_view_row.xml
> +                android:layout_marginEnd="10dp"
Do you need maybe to use things in style.xml and not hardcoded 10dp?

2023-05-18 15:16 UTC, KelvinKappeler commented on app/src/androidTest/java/com/github/sdp/tarjetakuna/ui/SingleCardManageCollectionTest.kt
> +        cardQuantityText.check(matches(withText("4")))
Maybe don't use hard-coded values here?

2023-05-18 15:16 UTC, KelvinKappeler commented on app/src/androidTest/java/com/github/sdp/tarjetakuna/ui/BrowserFragmentTest.kt
> +        onView(withId(R.id.browser_searchbar)).perform(typeText("Ambush Paratrooper 05"))
Maybe don't use hard-coded values here?

2023-05-18 17:18 UTC, Bjolidon commented
I added checks in my SingleCardFragment tests to check if the quantity of the DBMagicCards are updated accordingly

2023-05-18 17:26 UTC, KelvinKappeler approved these changes
Thanks for your changes!

2023-05-18 17:28 UTC, merged

2023-05-21 13:35 UTC, AlSchlo commented on app/src/androidTest/java/com/github/sdp/tarjetakuna/ui/SingleCardManageCollectionTest.kt
> +                        assert(it.quantity == 4)
Wrong assertion

2023-05-21 14:45 UTC, AlSchlo commented on app/src/androidTest/java/com/github/sdp/tarjetakuna/ui/SingleCardManageCollectionTest.kt
> +        Thread.sleep(1000)
😨