Activity to fragments
Tarjetakuna/Tarjetakuna pull request #24
Opened 2023-03-28 11:19 UTC by Cocograal

FilterActivity, UserCardsActivity, AuthenticationActivity, AuthenticationButtonActivity and SignOutActivity changed to their corresponding fragment.
The existing tests for these respective classes have been updated. Some tests still need to be created for some of the classes (which should have been done during the last sprint)
A test from AuthenticationButtonActivity has been commented with a TODO, because it does not pass the cirrus CI (it will need to be fixed in the future), but it passes all the local tests. It has been commented not to affect the progress of the project

2023-03-28 19:05 UTC, annierusu requested changes
Nice work! For some last nitpicking: check cirrus warnings for unused resources, document each file and function (even if it's just an obvious one liner) to keep consistency within our documentation. I have a question for the function we use to change the fragments: is this really the best way? I saw a method replace() that could be interesting. The main reason for my question is that we're always recreating instances of MainActivity...

2023-03-28 22:09 UTC, Cocograal commented on app/src/main/java/com/github/sdp/tarjetakuna/ui/authentication/AuthenticationButtonFragment.kt
> +    private fun setupErrorMsg() {
The source of this error does indeed not come from the view itself, but this function only displays the error on the screen

2023-03-28 22:13 UTC, Cocograal commented on app/src/main/java/com/github/sdp/tarjetakuna/ui/authentication/AuthenticationButtonViewModel.kt
> +
I could populate it, but there would only be an "if else" in it which would only complicate the code and make it less readable, so I am not sure whether it is the appropriate. I will ask on the group chat for your opinions and change it if necessary

2023-03-28 22:17 UTC, Cocograal commented on app/src/main/java/com/github/sdp/tarjetakuna/ui/authentication/AuthenticationButtonFragment.kt
I think this fragment is a transition one to transition between the states, I agree that it might be better to integrate it into AuthenticationFragment, but I am not sure whether there was a specific reason to implement it that way. I will ask the one that created the corresponding activity and see whether I should change it or not

2023-03-28 22:18 UTC, Cocograal commented on app/src/main/java/com/github/sdp/tarjetakuna/ui/authentication/SignOutViewModel.kt
I think so, yes because there is no computation done in the background, this fragment only contains a message and some buttons that lead to other fragments

2023-03-28 23:05 UTC, Cocograal commented
Cirrus warning for unused resources come from somewhere else and not from the part I am working on, I think that Kelvin has already created a pull request with the resolution of these warnings.
When we call requireActivity(), we do not create a new instance of mainActivity(), it is already in memory and we are just calling it back so I do not think there is a problem in the way we are changing the fragment views.

2023-03-29 14:33 UTC, Bjolidon commented on app/src/main/java/com/github/sdp/tarjetakuna/ui/authentication/AuthenticationButtonFragment.kt
I saw your discussion about this file. The main reason I did it that way was to check if the user was signed it before displaying the "Sign in button" and immediatly sending an intent to SignOutActivity if it is the case.
You could just replace it by merging the sign in and sign out button into the home fragment and change the visibility of the buttons accordingly to the user state

2023-03-29 14:33 UTC, Bjolidon commented on app/src/androidTest/java/com/github/sdp/tarjetakuna/AuthenticationButtonFragmentTest.kt
> +//    fun testAuthenticationButtonActivity() {
This test fails on my machine aswell. It is probably due to the fact that clicking the button will launch the external authentication page, and therefore the test doesn't catch the right currentDestination (Which is maybe null at the time?)

2023-03-29 14:33 UTC, Bjolidon commented on app/src/androidTest/java/com/github/sdp/tarjetakuna/SignOutFragmentTest.kt
Maybe change the test names as GreetingActivity doesn't exist anymore

2023-03-29 14:37 UTC, Cocograal commented on app/src/main/java/com/github/sdp/tarjetakuna/ui/authentication/AuthenticationButtonFragment.kt
I think we will change it later in another sprint as I have done more hours than necessary on this task, since it works well right now it is not something urgent to fix.

2023-03-29 14:40 UTC, Bjolidon commented on app/src/main/java/com/github/sdp/tarjetakuna/ui/authentication/AuthenticationButtonFragment.kt
Yes of course, it is not a problem as the functionality remains the same, I was just giving you some details as you asked for it.

2023-03-29 15:36 UTC, annierusu approved these changes
lgtm

2023-03-29 15:37 UTC, merged