30 api search jdt
Tarjetakuna/Tarjetakuna pull request #44
Opened 2023-03-30 19:52 UTC by JulienDiTria

api serach implements search such as:
- search cards by name
- search card by id
- serach cards by set code
- search set by set code

2023-04-14 11:05 UTC, KelvinKappeler requested changes
Thank you for your work. Don't forget to comment on the classes and methods including in the tests package so that we know more quickly the interest of certain features!

2023-04-14 11:18 UTC, KelvinKappeler commented
I wanted to just add something else :
Why didn't you use the tools made available to you from the Magic API? For example, I see that you created a MagicCard in WebApi when it already exists in the magic API documentation: 

https://github.com/MagicTheGathering/mtg-sdk-kotlin/blob/develop/src/io/magicthegathering/kotlinsdk/model/card/MtgCard.kt

2023-04-14 16:36 UTC, merged

2023-04-21 07:53 UTC, SolalPirelli commented on app/src/main/java/com/github/sdp/tarjetakuna/ui/webapi/WebApiFragment.kt
>          }
Looks like those listeners have a lot of common code that could be factored into one reusable function

2023-04-21 07:55 UTC, SolalPirelli commented on app/src/test/java/com/github/sdp/tarjetakuna/ui/webapi/WebApiTest.kt
> +        assert(api.magicUrl == url)
What's the point of this test? And why does it not use JUnit asserts?