Scan fragment
Tarjetakuna/Tarjetakuna pull request #9
Opened 2023-03-13 10:41 UTC by KelvinKappeler

Implementation of the scan fragment and its tests.
This fragment allows you to take a picture and (for the moment) just display it with a text explaining if the operation was successful.
100% coverage tests.

2023-03-14 15:01 UTC, Cocograal requested changes
Overall the code is good, just do not forget the end lines

2023-03-14 15:01 UTC, Cocograal commented on app/src/main/java/com/github/bjolidon/bootcamp/utils/Compatibility.kt
> +}
add end line

2023-03-14 15:01 UTC, Cocograal commented on app/src/main/res/layout/fragment_scanner.xml
>  </androidx.constraintlayout.widget.ConstraintLayout>
add end line

2023-03-14 15:04 UTC, KelvinKappeler commented on app/src/main/java/com/github/bjolidon/bootcamp/ui/scanner/ScannerFragment.kt
> +}
Already there

2023-03-14 15:16 UTC, Cocograal approved these changes
All is good now!

2023-03-14 15:25 UTC, merged

2023-03-24 09:40 UTC, SolalPirelli commented on app/src/main/java/com/github/bjolidon/bootcamp/ui/scanner/ScannerFragment.kt
> +    private val binding get() = _binding!!
It looks like this is (still) unused and could be removed?